<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <div class="col-xl-10 col-lg-9 justify-content-center">
    <div class="row container">
         <div class="col-md-6">
                <img src="../image/hero-img.png" class="d-lg-block d-none"  alt="">
         </div>
         <div class="col-md-6">
        <form class="shadow-sm p-5  rounded" action="<?=$SERVER['PHP_SELF']?>" method="post">
            <h1 class="text-center">Sign Up</h1>
            <label>Nom</label>
            <input type="text" name="name" class="form-control">
      </form>
      </div>
      </div>
   </div>
</body>
</html>