<style>
    img{
        width: 100%;
        height: 100%;
    }
</style>

<div class="d-flex p-3 m-4 justify-content-center">   
    <div class="col-xl-10 col-md-12 col-lg-12">
          <div class="row shadow-lg rounded">
                <div class="col-lg-6 d-none d-lg-block bg-secondary">
                    <img src="../assets/image/account.png" alt="">
                </div>
                <div class=" col-lg-6 py-5">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-5">Welcome Back !</h1>
                      </div>
                    <form action="<?=$_SERVER['PHP_SELF'] ?>" method="POST">
                    <?php if(array_key_exists('msg',$_GET)): ?>  
                       <div class="alert alert-<?=$_GET['type']?>">
                                <?=$_GET['msg'];?>
                        </div>
                        <?php endif; ?>
                      <div class="mb-4">
                          <input  type="text" placeholder="Entrer Email Address..." name="email" class="form-control rounded-pill p-4" id="exampleInputEmail1">
                      </div>
                      <div class="mb-5">
                         <input type="password" placeholder="Password" name="password" class="form-control rounded-pill p-4" id="exampleInputPassword1">
                      </div>
                          <button style="font-size:19px" type="submit" name="submit" class="btn btn-primary btn-block w-100 rounded-pill">Login</button>
                      </form>
                      <hr>
                      <div class="fin text-center py-4 mb-1">
                              <a href="##">Forgot Password ?</a>
                       </div>
                       <div class="fin text-center">
                              <a href="../signup">Create an Account !</a>
                      </div> 
                </div>
          </div>
    </div>
</div>