
<div class="d-flex p-3 m-4 justify-content-center">   
    <div class="col-xl-10 col-md-12 col-lg-12">
          <div class="row shadow-lg rounded">
                <div class="col-lg-6">
                        <div class="text-center">
                           <h1 class="h4 fw-bolder mb-3 py-3">Sign Up</h1>
                        </div>
                        <!--novalidate=""-->
                    <form class="py-4" action="index.php" method="POST"  enctype="multipart/form-data">
                  
                       <div class="row mb-4 ">
                          <div class="col-lg-6">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control " >
                            <small class="text-danger" ><?= array_key_exists('name',$error) ? $error['name'] : '' ?></small>
                          </div>
                          <div class="col-lg-6">
                            <label>Prenom</label>
                            <input type="text" name="prenom" class="form-control ">
                            <small class="text-danger" ><?= array_key_exists('prenom',$error) ? $error['prenom'] : '' ?></small>
                          </div>
                        </div>
                        <div class="row mb-4">
                          <div class="col-lg-6 form-group">
                            <label>email</label>
                            <input type="email" name="email" class="form-control ">
                            <small class="text-danger" ><?= array_key_exists('email',$error) ? $error['email'] : '' ?></small>
                          </div>
                          <div class="col-lg-6">
                            <label>Password</label>
                            <input type="password" name="password"  class="form-control" >
                            <small class="text-danger" ><?= array_key_exists('password',$error) ? $error['password'] : '' ?></small>
                              <div>
                                 <small class="text-danger">shoul be more than 6 caractere</small>
                                 <br>
                                 <small class="text-danger">shoul be numerique and alphabetique</small>
                                 <br>
                                 <small class="text-danger">shoul be have one special caractere</small>
                              </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-lg-12">
                            <label>Avatar</label>
                            <input type="file" name="avatar" class="form-control ">
                            <small class="text-danger" ><?= array_key_exists('file',$error) ? $error['file'] : '' ?></small>
                          </div>
                        </div>
                        <!--<div class="form-group text-center py-4">
							          	<input type="checkbox" name="agree" id="agree" class="custom-control-input">
								          <label for="agree" class="custom-control-label">I agree to the <a href="#">Terms and Conditions</a></label>
						            </div>-->
                        <div class="text-center mt-2">
                             <button name="signup" class="btn btn-outline-success">Sign Up</button>
                        </div>
                        <div class="mt-4 text-muted text-center">
								            Already have an account ? <a href="../login">Login</a>
					            </div>
                    </form>
                </div>
                <div class="col-lg-6 d-none d-lg-block bg-secondary">
                    <img src="../assets/image/hero-img.png" alt="">
                </div>
          </div>
    </div>
</div>
