

  <header class="p-2 mb-4 border-bottom">
    <div class="container">
      <div class="d-flex justify-content-center">
        <div class="dropdown text-center">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="<?=$_SESSION['avataruser']?>" alt="mdo" width="52" height="52" class="rounded-circle">
          </a>
           <h4 class="py-2"><?=$_SESSION['nameuser']?></h4>
          <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="../log_out.php">Log out</a></li>
          </ul>
        </div>
      </div>
    </div>
  </header>


  <div class="text-center">
    <a href="../add_todo"><button class="btn btn-outline-primary">add Todo</button></a>
     <div class="mt-5 py-4 container">
         <?php if(array_key_exists('msg',$_GET)): ?>
             <div class="alert alert-<?=$_GET['type']?>">
                <?=$_GET['msg']?>
             </div>
         <?php endif; ?>
         <table class="table table-bordered">
            <tr>
              <th>*</th>
              <th>Id</th>
              <th>Titel</th>
              <th>operation</th>
            </tr>
            
              <?php if(empty($alltodos)): ?>
                <tbody>
                    <tr class="bg-danger">
                        <td colspan="6" class="text-white">vide</td>
                    </tr>
                </tbody>
             <tr>
              <?php else:?>
                <tbody>
                    <?php foreach($alltodos as $value): ?>  
                       <tr>
                           <td>
                           <form action="../checkedtodo.php" method="GET">
                            <input type="hidden" name="id" value="<?=$value['id']?>">
                            <input onChange="this.form.submit()" type="checkbox"<?=$value['complete'] ? 'checked':'';?>>
                          </form>
                        </td>
                          <td><?=$value['id']?></td>
                        <td class="<?=$value['complete'] ? 'text-decoration-line-through':'';?>"><?=$value['titel']?></td>
                        <td>
                        <button  class="btn btn-info"  data-bs-toggle="modal" data-bs-target="#exampleedit<?=$value['id'];?>">consulte</button>
                          <div class="modal fade" id="exampleedit<?=$value['id'];?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Info  Todo :</h5>
                                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></a>
                                  </div>
                                  <div class="modal-body">
                                      <div class="card">
                                          <div class="card-header">
                                             <span class="font-weight-bold"><?=$value['titel']?></span>
                                          </div>
                                          <div class="card-body">
                                            <div class="col-xl-8 container d-flex justify-content-center">
                                              <div class="row ">
                                                  <div class="col-lg-6">
                                                         <span class="text-primary"> description :</span>
                                                  </div>
                                                  <div class="col-lg-6">
                                                          <?=$value['description']?>
                                                  </div>
                                                  <div class="col-lg-6 fw-bolder">
                                                  <span class="text-primary"> due date :</span>
                                                  </div>
                                                  <div class="col-lg-6">
                                                  <?=$value['due_date']?>
                                                  </div>
                                              </div>
                                              </div>
                                          </div>
                                      </div>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                  </div>
                                </div>
                              </div>
                            </div>
                          <button class="btn btn-danger " data-bs-toggle="modal" data-bs-target="#exampleModal<?=$value['id'];?>">Delete</button>
                          <a href="../edit?id=<?=$value['id']?>"><button  class="btn btn-warning">edit</button></a>
                        </td>
                             <div class="modal fade" id="exampleModal<?=$value['id'];?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel<?=$value['id'];?>">Delete Book :</h5>
                                   <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></a>
                                  </div>
                                  <div class="modal-body">
                                      Do you want delete todo <?=$value['titel'];?> ?
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    <a href="../delete_todo.php?id=<?=$value['id']?>"> <button type="button" class="btn btn-danger">Delete</button></a>
                                  </div>
                                </div>
                              </div>
                            </div>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
              <?php endif; ?>
             </tr>
         </table>
     </div>
  </div>
